services:
  - type: web
    name: lobilend-api
    runtime: docker
    plan: free
    region: virginia
    dockerfilePath: ./Dockerfile.api
    dockerContext: .
    healthCheckPath: /api/v1/auth/csrf
    domains:
      - api.lobilend.com
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__BrokerApp
        sync: false
      - key: Cors__AllowedOrigins__0
        value: https://lobilend.com
      - key: Cors__AllowedOrigins__1
        value: https://unrivaled-eclair-d5927d.netlify.app
      - key: Frontend__BaseUrl
        value: https://lobilend.com
      - key: Auth__RequireConfirmedEmail
        value: "true"
      - key: Email__Provider
        value: Mailgun
      - key: Email__Mailgun__BaseUrl
        value: https://api.mailgun.net
      - key: Email__Mailgun__Domain
        value: lobilend.com
      - key: Email__Mailgun__FromAddress
        value: postmaster@lobilend.com
      - key: Email__Mailgun__FromName
        value: LobiLend
      - key: Email__Mailgun__ApiKey
        sync: false
      - key: Auth__OpenIddict__EncryptionCertificateBase64
        sync: false
      - key: Auth__OpenIddict__EncryptionCertificatePassword
        sync: false
      - key: Auth__OpenIddict__SigningCertificateBase64
        sync: false
      - key: Auth__OpenIddict__SigningCertificatePassword
        sync: false
